#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

FROM quay.io/canuunac/cann:9.1.0.B110-a3-openeuler24.03-lts-sp4-py3.12

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

SHELL ["/bin/bash", "-c"]

# Install clang (for triton-ascend) and Mooncake
ARG MOONCAKE_TAG=0.3.11.post1
RUN yum update -y && \
    yum install -y git vim wget net-tools gcc gcc-c++ make cmake numactl numactl-devel libibverbs-devel jemalloc hiredis-devel clang patch pciutils unzip && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    python3 -m pip install mooncake-transfer-engine-npu==${MOONCAKE_TAG} --extra-index-url https://mirrors.aliyun.com/pypi/web/simple && \
    rm -rf /var/cache/yum/*

# Install modelscope (for fast download) and ray (for multinode)
RUN pip config set global.index-url ${PIP_INDEX_URL} && \
    python3 -m pip install modelscope 'ray>=2.47.1,<=2.48.0' 'protobuf>3.20.0' && \
    python3 -m pip cache purge

# download routeserver
RUN wget -O /root/DistributedScheduler-6.5.930-20260721210039.zip https://obs-prod-wl-1.obs.cn-north-9.myhuaweicloud.com:443/scripts/DistributedScheduler-6.5.930-20260721210039.zip?AccessKeyId=HSTAB2NXO4LCMFRWMEUH&Expires=1784826046&x-obs-security-token=hQpjbi1zb3V0aC0xAQAABStIU1RBQjJOWE80TENNRlJXTUVVSCWGneGrsfdzzUvBo4EeWDMxOP4hmbgvw-L6BB6JfE1dhjedxZ4KR9xCBm6lEyBr0_npgWJN88e-qs6qX5lyJscsWr9ashjjXLxTcFreyRLBtfw5pgr18wuKWE6wjiovUuXjse8MIDpOU6--qBliC-K4LvX4I93FAodhQN05Xi5FjMvkjhJyVlsdX6qfvJ5q0jwhJnuVgbVi9BmqfX2A-hQmYkJLW1V4WiXbIfvqK10aWJA9aqBu9sePH9zTuaBBnXS3DrtofsfIfTSzacHSR2RxicWf-IfhXTMcSMyIdWfhpaqy67AsqrSzqaM5iuNYMMOUAktVu7QRxwd5cI-KgNvNrmWzV9NkotJNbqwfNLA2eOg69C2HgBIlFNn5gNmwWzdZ8U-I2wf1Ltb-TyF6jVS5KmdPFu-VX3iAKvv-RhMuJWD6a5AwyFAM2rQQpn01N4kjN7ZhbllntxD9jIb0_04Q7zO9JQSIFOXa8lgMEVC5q_Ts2aEqcr9sIABlDo6YOUgqFlc9tlxYG9dVRszDmH1O7EVUtZE2oIcMfPpO7uN1xpuJW65yooncknVmKrykVmurJWntsbu385od_nxbAzI79rsxT_Q%3D&Signature=5RudU3xKaTwLSkVXdjYmQilCsAU%3D
# RUN  curl --progress-bar -fSL -o /root https://cmc-nkg-artifactory.cmc.tools.huawei.com/artifactory/hwcloud-artifact/cloudbuild2.0/10123511/38D25NV1-P45E-T680-0000-8CAD0KHGt3Au/1784638979956/38D25NV1-P45E-T680-0000-8CAD0KHGt3Au/DistributedScheduler-6.5.930-20260721210039.zip
# ADD https://cmc-nkg-artifactory.cmc.tools.huawei.com/artifactory/hwcloud-artifact/cloudbuild2.0/10123511/38D25NV1-P45E-T680-0000-8CAD0KHGt3Au/1784638979956/38D25NV1-P45E-T680-0000-8CAD0KHGt3Au/DistributedScheduler-6.5.930-20260721210039.zip /root/ 
RUN ls /root
RUN unzip /root/DistributedScheduler-6.5.930-20260721210039.zip 


WORKDIR /workspace

# Install vLLM
ARG VLLM_REPO=https://github.com/jerry-zsw/vllm-jerry.git
ARG VLLM_TAG=0.23.0-tag-rank-computing
ARG VLLM_COMMIT=""
RUN if [ -n "$VLLM_COMMIT" ]; then \
      git init /vllm-workspace/vllm && \
      git -C /vllm-workspace/vllm fetch --depth 1 $VLLM_REPO "$VLLM_COMMIT" && \
      git -C /vllm-workspace/vllm checkout FETCH_HEAD; \
    else \
      git clone --depth 1 -b $VLLM_TAG $VLLM_REPO /vllm-workspace/vllm; \
    fi
# In x86, triton will be installed by vllm. But in Ascend, triton doesn't work correctly. we need to uninstall it.
RUN VLLM_TARGET_DEVICE="empty" python3 -m pip install -e /vllm-workspace/vllm/[audio] --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton && \
    python3 -m pip cache purge

# Install vllm-ascend
ARG SOC_VERSION="ascend910_9391"
ARG COMPILE_CUSTOM_KERNELS=1
ENV SOC_VERSION=$SOC_VERSION \
    TASK_QUEUE_ENABLE=1 \
    OMP_NUM_THREADS=1
COPY . /vllm-workspace/vllm-ascend/

RUN export PIP_EXTRA_INDEX_URL="https://mirrors.huaweicloud.com/ascend/repos/pypi" && \
    export VLLM_BATCH_INVARIANT=1 && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    python3 -m pip install -e /vllm-workspace/vllm-ascend/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton triton-ascend && \
    python3 -m pip install triton-ascend==3.2.1 --extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi && \
    python3 -m pip cache purge

RUN echo "export LD_PRELOAD=/usr/lib64/libjemalloc.so.2:$LD_PRELOAD" >> ~/.bashrc
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> ~/.bashrc

RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && source /usr/local/Ascend/cann-9.1.0/share/info/ascendnpu-ir/bin/set_env.sh && source /usr/local/Ascend/nnal/atb/set_env.sh --cxx_abi=1
ENV CANN_VERSION=9.1.0

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

CMD ["/bin/bash"]
